name: My script

on: 
  # once every day in 4am UTC
  schedule:
  - cron:  "0 4 */2 * *"

jobs:
 job:
  # OS and timeout
  runs-on: ubuntu-latest
  timeout-minutes: 20

  steps:
  # few dependencies or something idk
  - uses: actions/checkout@v3
  - uses: actions/setup-python@v3
  # using pip cache
    with:
      cache: 'pip'
  

  # installing dependencies
  - run: pip install -r requirements.txt
  # converting jupyter notebook to python
  - run: jupyter nbconvert --to python covid_stats.ipynb
  # runing main python file (it executes other stuff)
  - name: Main part
    env:
      SENDER_EMAIL: ${{ secrets.SENDER_EMAIL }}
      SENDER_PASSWORD: ${{ secrets.SENDER_PASSWORD }}
      RECIVER_EMAIL: ${{ secrets.RECIVER_EMAIL }}
    run: python3 main.py