name: My script

on: 
  # once every day in 4am UTC
  schedule:
  - cron:  "0 4 */2 * *"

jobs:
 job:
  # OS and timeout ()
  runs-on: ubuntu-latest
  timeout-minutes: 20

  steps:
  # propably useless, too scared to delete it
  - uses: actions/checkout@v3
  - uses: actions/setup-python@v3
  # using pip cache
    with:
      cache: 'pip'
  

  # install dependencies
  - run: sudo apt-get install -y python3-feedparser python3-numpy python3-pandas python3-matplotlib python3-requests jupyter-notebook jupyter-nbconvert
  # converting jupyter notebook to python
  - run: jupyter nbconvert --to python covid_stats.ipynb
  # runing main python file (it executes other stuff)
  - name: Main part
    env:
      SENDER_EMAIL: ${{ secrets.SENDER_EMAIL }}
      SENDER_PASSWORD: ${{ secrets.SENDER_PASSWORD }}
      RECIVER_EMAIL: ${{ secrets.RECIVER_EMAIL }}
      OTHER_URLS: ${{ secrets.OTHER_URLS }}
    run: python3 main.py